export const INIT_FRUITS = 'INIT_FRUITS';
export const DOC_SIZE = 'DOC_SIZE';
export const INIT_FRUITS_SUCCESS = 'INIT_FRUITS_SUCCESS';
export const INIT_FRUITS_FAILS = 'INIT_FRUITS_FAILS';
export const GET_FRUIT_SUCCESS = 'GET_FRUIT_SUCCESS';

export const INIT_FRUIT_IMG = 'INIT_FRUIT_IMG';
export const INIT_FRUIT_IMG_SUCCESS =
  'INIT_FRUIT_IMG_SUCCESS';
export const GET_FRUIT_IMG_2_SUCCESS =
  'GET_FRUIT_IMG_2_SUCCESS';
export const INIT_FRUIT_IMG_FAILED =
  'INIT_FRUIT_IMG_FAILED';

export const LOGIN_BEGINS = 'LOGIN_BEGINS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const AUTH_LOGOUT_BEGINS = 'AUTH_LOGOUT_BEGINS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';

export const ADD_FRUIT_BEGINS = 'ADD_FRUIT_BEGINS';
export const ADD_FRUIT_SUCCESS = 'ADD_FRUIT_SUCCESS';
export const ADD_FRUIT_FAIL = 'ADD_FRUIT_FAIL';
